- name: install {{ openstack_release }}
  package: name=centos-release-openstack-{{ openstack_release }} state=latest

- name: install support files for {{ openstack_release }}
  package: name={{ item }} state=latest
  with_items:
    - python-openstackclient
    - openstack-selinux

- name: setup limits
  copy: src=limits-openstack.conf dest=/etc/security/limits.d/30-openstack.conf 

- name: generate environment
  lineinfile: line="export {{ item.key }}={{ item.value }}" dest=/root/openstack-admin.rc state=present create=yes
  tags: config
  with_dict: "{{ openstack_env }}"

- name: make workdir
  tags: config
  local_action: file dest={{ inventory_dir }}/workdir state=directory
  run_once: true

- name: generate services.xml
  tags:
    - config
    - clinit
  local_action: template src="services.xml.j2" dest={{ inventory_dir }}/workdir/services.xml
  run_once: true
